version: '3'

services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
      - "--mysql.address=192.168.147.139"

  user-edge-service:
    image: user-edge-service:latest
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=192.168.147.139"

  course-service:
    image: course-service:latest
    links:
      - user-service
    command:
      - "--mysql.address=192.168.147.139"
      - "--zookeeper.address=192.168.147.139"

  course-edge-service:
    image: course-edge-service:latest
    links:
      - user-edge-service
    command:
      - "--zookeeper.address=192.168.147.139"
    ports:
      - 8083:8083